package com.example.beon.designsystem.tokens

import androidx.compose.ui.graphics.Color

/**
 * Primitive color palette for the BeOn streaming platform.
 *
 * These values mirror the `primitives.json` token file generated by the
 * Figma Make pipeline. They are intentionally raw — UI code should never
 * consume these directly. Instead consume the semantic [BeOnColors] via
 * `BeOnTheme.colors`.
 */
internal object BeOnPalette {
    val Black = Color(0xFF000000)
    val White = Color(0xFFFFFFFF)

    val Gray50 = Color(0xFFFAFAFA)
    val Gray100 = Color(0xFFF5F5F5)
    val Gray200 = Color(0xFFE5E5E5)
    val Gray300 = Color(0xFFD4D4D4)
    val Gray400 = Color(0xFFA0A0A0)
    val Gray500 = Color(0xFF737373)
    val Gray600 = Color(0xFF52525B)
    val Gray700 = Color(0xFF404040)
    val Gray800 = Color(0xFF333333)
    val Gray850 = Color(0xFF1E1E1E)
    val Gray900 = Color(0xFF1A1A1A)
    val Gray950 = Color(0xFF121212)

    val Green400 = Color(0xFF4ADE80)
    val Green500 = Color(0xFF22C55E)
    val Green600 = Color(0xFF16A34A)
    val Green700 = Color(0xFF15803D)
    val GreenAccent = Color(0xFF05DF72)
    val GreenHover = Color(0xFF04C665)

    val Red400 = Color(0xFFF87171)
    val Red500 = Color(0xFFEF4444)
    val Red600 = Color(0xFFDC2626)
    val RedError = Color(0xFFFF4D4D)

    val Yellow400 = Color(0xFFFACC15)
    val Yellow500 = Color(0xFFFDC700)

    val Transparent = Color(0x00000000)
}
